@api = http://localhost:3000
###
GET {{api}}/game

###
GET {{api}}/game/5fb920122804272e2c4d4040

###
POST {{api}}/game/
Content-Type: application/json

{
    "name": "TFT",
    "genre": "Strategy",
    "ratingId" : "5fb91f812804272e2c4d403e",
    "image": "https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/bltfe81204b8ec63e0e/5e6184a918d3347ceffbbd6d/TFT.S3_GALAXIES.ARTICLE-2.jpg",
    "description": "Juego de cartas"
}

###
DELETE {{api}}/game/5fb002dfc3106f47f027f87f

###
PUT {{api}}/game/5fb956b86980101d50479c0e
Content-Type: application/json

{
    "name":"Cs 1.6 No Steam",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSN_8E-4unZJZ8_FQlEfJYSBlN45rC4ICnSg&usqp=CAU"
}